Merge TestStatus and Readme
ArasLabs/dashboard-customizations pull request #2
Opened 2019-03-05 16:31 UTC by sampoearas

Tested on 11.0 SP12, SP15

2019-03-05 16:42 UTC, EliJDonahue requested changes
* Built and tested on 11 **SP9**, not SP7. 
* Include the FF issue and lack of Chrome support in the release notes table entry for v1.0.1.

2019-03-05 18:24 UTC, sampoearas commented
Readme Updated: FF issue moved. SP listing updated.

2019-03-07 21:40 UTC, EliJDonahue requested changes

2019-03-07 21:40 UTC, EliJDonahue commented on README.md
> +> Though built and tested using Aras 11.0 SP9, this project should function in older releases of Aras 11.0 and Aras 10.0.
This line can be removed. Now we have the supported versions table to convey this info.
```suggestion

```

2019-03-07 21:40 UTC, EliJDonahue commented on README.md
> +[v1.0.1](https://github.com/ArasLabs/dashboard-customizations/releases/tag/v1.0.1) | Tested 11.0 SP12, SP15. Tested on Edge, IE, ~~Firefox 60 ESR, Chrome.~~ **Package works in IE, Edge. [Has axis err
```suggestion
[v1.0.1](https://github.com/ArasLabs/dashboard-customizations/releases/tag/v1.0.1) | Tested 11.0 SP12, SP15. Package works in IE, Edge. [Has axis error in Firefox (Issue).](https://github.com/ArasLabs/dashboard-customizations/issues/1) Chrome not supported at this time.
```

2019-03-07 21:42 UTC, sampoearas commented
changes accepted. Please merge.

2019-03-07 21:43 UTC, EliJDonahue approved these changes

2019-03-07 21:43 UTC, merged